### ISSUE TITLE
dw can't parse comment of xml

### ISSUE THREAD

**Issue by larrylau** [mulesoft-labs/data-weave-native#22]
**Describe the bug**
dw can't parse comment of  xml 

**To Reproduce**
 1. I create a xml named a.xml
 ``` xml
<a>
	<!-- aa -->
	<b>test</b>
</a>
 ```
 2.  I use dw convert a.xml to json 
 ```
 dw -i payload a.xml "output application/json --- payload"
```
 3.  I got this error message
 ```
[31mError while executing the script:[0m
[31mscala.MatchError - 5 (of class java.lang.Integer)
scala.MatchError: 5 (of class java.lang.Integer)
        at org.mule.weave.v2.module.xml.reader.InMemoryXmlParserHelper$.parseStreamingNonNullValue(InMemoryXmlParserHelper.scala:148)
        at org.mule.weave.v2.module.xml.reader.InMemoryXmlParserHelper$.parseLazyValue(InMemoryXmlParserHelper.scala:138)
        at org.mule.weave.v2.module.xml.reader.InMemoryXmlParserHelper$.$anonfun$parseStreamingNonNullValue$2(InMemoryXmlParserHelper.scala:161)
        at org.mule.weave.v2.model.values.wrappers.LazyValue.value(DelegateValue.scala:79)
        at org.mule.weave.v2.model.values.wrappers.DelegateValue.evaluate(DelegateValue.scala:22)
        at org.mule.weave.v2.model.values.wrappers.DelegateValue.evaluate$(DelegateValue.scala:22)
        at org.mule.weave.v2.model.values.wrappers.LazyValue.evaluate(DelegateValue.scala:73)
        at org.mule.weave.v2.module.json.writer.JsonWriter.doWriteValue(JsonWriter.scala:154)
        at org.mule.weave.v2.module.writer.WriterWithAttributes.internalWriteValue(WriterWithAttributes.scala:35)
        at org.mule.weave.v2.module.writer.WriterWithAttributes.internalWriteValue$(WriterWithAttributes.scala:34)
        at org.mule.weave.v2.module.json.writer.JsonWriter.internalWriteValue(JsonWriter.scala:28)
        at org.mule.weave.v2.module.writer.WriterWithAttributes.writeAttributesAndValue(WriterWithAttributes.scala:30)
        at org.mule.weave.v2.module.writer.WriterWithAttributes.writeAttributesAndValue$(WriterWithAttributes.scala:15)
        at org.mule.weave.v2.module.json.writer.JsonWriter.writeAttributesAndValue(JsonWriter.scala:28)
        at org.mule.weave.v2.module.json.writer.JsonWriter.writeObject(JsonWriter.scala:94)
        at org.mule.weave.v2.module.json.writer.JsonWriter.doWriteValue(JsonWriter.scala:155)
        at org.mule.weave.v2.module.writer.Writer.writeValue(Writer.scala:41)
        at org.mule.weave.v2.module.writer.Writer.writeValue$(Writer.scala:39)
        at org.mule.weave.v2.module.json.writer.JsonWriter.writeValue(JsonWriter.scala:28)
        at org.mule.weave.v2.module.writer.DeferredWriter.doWriteValue(DeferredWriter.scala:73)
        at org.mule.weave.v2.module.writer.Writer.writeValue(Writer.scala:41)
        at org.mule.weave.v2.module.writer.Writer.writeValue$(Writer.scala:39)
        at org.mule.weave.v2.module.writer.DeferredWriter.writeValue(DeferredWriter.scala:16)
        at org.mule.weave.v2.module.writer.WriterHelper$.writeValue(Writer.scala:120)
        at org.mule.weave.v2.module.writer.WriterHelper$.writeAndGetResult(Writer.scala:98)
        at org.mule.weave.v2.interpreted.InterpretedMappingExecutableWeave.writeWith(InterpreterMappingCompilerPhase.scala:235)
        at org.mule.weave.v2.runtime.DataWeaveScript.doWrite(DataWeaveScriptingEngine.scala:459)
        at org.mule.weave.v2.runtime.DataWeaveScript.write(DataWeaveScriptingEngine.scala:416)
        at org.mule.weave.dwnative.NativeRuntime.run(NativeRuntime.scala:124)
        at org.mule.weave.dwnative.cli.DataWeaveCLIRunner.run(DataWeaveCLI.scala:370)
        at org.mule.weave.dwnative.cli.DataWeaveCLIRunner.run(DataWeaveCLI.scala:58)
        at org.mule.weave.dwnative.cli.DataWeaveCLI$.delayedEndpoint$org$mule$weave$dwnative$cli$DataWeaveCLI$1(DataWeaveCLI.scala:33)
        at org.mule.weave.dwnative.cli.DataWeaveCLI$delayedInit$body.apply(DataWeaveCLI.scala:29)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at org.mule.weave.dwnative.cli.DataWeaveCLI$.main(DataWeaveCLI.scala:29)
        at org.mule.weave.dwnative.cli.DataWeaveCLI.main(DataWeaveCLI.scala), while writing Json at payload. at:
payload[0m
```
4. remove comment  in xml ,its working.

**Comment by machaval** [comment]
This issue has been fixed on latest version
