### ISSUE TITLE
NPE when using `-path`

### ISSUE THREAD

**Issue by jerneyio** [mulesoft-labs/data-weave-native#9]
**Describe the bug**
NPE when using `-path`

**To Reproduce**

```
DIRECTORY=<pick your directory>

cd $DIRECTORY

echo '%dw 2.0
fun addUnderscore(s) = s ++ "_"
` > utils.dwl

dw -path $DIRECTORY 'output application/json import * from utils --- { hello: addUnderscore("world") }'
```
Here's the stack trace:

```
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:35)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.mule.weave.dwnative.PathBasedResourceResolver.recursiveListFiles(PathBasedResourceResolver.scala:64)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$recursiveListFiles$1(PathBasedResourceResolver.scala:68)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$recursiveListFiles$1$adapted(PathBasedResourceResolver.scala:64)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.mule.weave.dwnative.PathBasedResourceResolver.recursiveListFiles(PathBasedResourceResolver.scala:64)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$recursiveListFiles$1(PathBasedResourceResolver.scala:68)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$recursiveListFiles$1$adapted(PathBasedResourceResolver.scala:64)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.mule.weave.dwnative.PathBasedResourceResolver.recursiveListFiles(PathBasedResourceResolver.scala:64)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$loadResources$1(PathBasedResourceResolver.scala:45)
	at org.mule.weave.dwnative.PathBasedResourceResolver.$anonfun$loadResources$1$adapted(PathBasedResourceResolver.scala:22)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:39)
	at org.mule.weave.dwnative.PathBasedResourceResolver.loadResources(PathBasedResourceResolver.scala:22)
	at org.mule.weave.dwnative.PathBasedResourceResolver.entries$lzycompute(PathBasedResourceResolver.scala:73)
	at org.mule.weave.dwnative.PathBasedResourceResolver.entries(PathBasedResourceResolver.scala:73)
	at org.mule.weave.dwnative.PathBasedResourceResolver.resolve(PathBasedResourceResolver.scala:76)
	at org.mule.weave.v2.parser.phase.ResourceBasedModuleParser.loadModule(ModuleLoader.scala:126)
	at org.mule.weave.v2.parser.phase.ModuleLoaderManager.$anonfun$loadModule$3(ModuleLoader.scala:80)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
	at org.mule.weave.v2.parser.phase.ModuleLoaderManager.$anonfun$loadModule$2(ModuleLoader.scala:79)
	at scala.Option.flatMap(Option.scala:188)
	at org.mule.weave.v2.parser.phase.ModuleLoaderManager.loadModule(ModuleLoader.scala:77)
	at org.mule.weave.v2.parser.phase.DefaultModuleParserManager.parseModule(ModuleParserManager.scala:94)
	at org.mule.weave.v2.parser.phase.CompositeModuleParserManager.$anonfun$parseModule$2(ModuleParserManager.scala:179)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.mule.weave.v2.parser.phase.CompositeModuleParserManager.parseModule(ModuleParserManager.scala:179)
	at org.mule.weave.v2.parser.phase.ParsingContext.tryToParseModule(ParsingContext.scala:98)
	at org.mule.weave.v2.parser.phase.ImportsValidation.$anonfun$checkImports$2(ImportsValidation.scala:16)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.mule.weave.v2.parser.phase.ImportsValidation.checkImports(ImportsValidation.scala:13)
	at org.mule.weave.v2.parser.phase.ImportsValidation.transform(ImportsValidation.scala:31)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.$anonfun$doTransform$1(AstNodeTransformationPhase.scala:8)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.$anonfun$doTransform$1$adapted(AstNodeTransformationPhase.scala:8)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.doTransform(AstNodeTransformationPhase.scala:8)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.traverse(AstNodeTransformationPhase.scala:12)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.call(AstNodeTransformationPhase.scala:17)
	at org.mule.weave.v2.parser.phase.AstNodeTransformationPhase.call(AstNodeTransformationPhase.scala:5)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:31)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:27)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:27)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:31)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:27)
	at org.mule.weave.v2.parser.phase.CompositeCompilationPhase.call(CompilationPhase.scala:27)
	at org.mule.weave.v2.parser.MappingParser$.parse(MappingParser.scala:71)
	at org.mule.weave.dwnative.NativeRuntime.run(NativeRuntime.scala:71)
	at org.mule.weave.dwnative.cli.DataWeaveCLIRunner.run(DataWeaveCLI.scala:169)
	at org.mule.weave.dwnative.cli.DataWeaveCLIRunner.run(DataWeaveCLI.scala:39)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$.delayedEndpoint$org$mule$weave$dwnative$cli$DataWeaveCLI$1(DataWeaveCLI.scala:23)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$delayedInit$body.apply(DataWeaveCLI.scala:20)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$.main(DataWeaveCLI.scala:20)
	at org.mule.weave.dwnative.cli.DataWeaveCLI.main(DataWeaveCLI.scala)
```

**Expected behavior**
I would expect this to output `{ "hello": "world_" }`

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

**Comment by jerneyio** [comment]
Still a bug as of 9/14/19. Maybe the download link in the README.md needs to be updated?

**Comment by SGmuwa** [comment]
https://github.com/mulesoft-labs/data-weave-cli/issues/6#issuecomment-531321245
